@host = http://localhost:5223
@internalSecret = replace-with-at-least-32-bytes
@userId = 9000000000000001
@storyId = 9000000000000002
@postId = 9000000000000003
@groupPostId = 9000000000000004
@groupId = 9000000000000005

POST {{host}}/graphql
Content-Type: application/json
X-Correlation-ID: manual-register-test

{
  "query": "mutation CreateUser($input: CreateUserInput!) { createUser(input: $input) { success userId message } }",
  "variables": {
    "input": {
      "name": "Nguyen Van A",
      "gender": true,
      "birthdate": "2000-01-01",
      "location": "Ha Noi",
      "email": "a@example.com",
      "password": "secret123"
    }
  }
}

###

POST {{host}}/graphql
Content-Type: application/json
X-Gateway-Secret: {{internalSecret}}
X-User-Id: {{userId}}
X-Correlation-ID: manual-create-story-test

{
  "query": "mutation CreateNormalStory($input: CreateNormalStoryInput!) { createNormalStory(input: $input) { id content create media { id type url } } }",
  "variables": {
    "input": {
      "authorId": {{userId}},
      "content": "Story text",
      "media": {
        "type": 0,
        "url": "https://cdn.local/story.jpg"
      }
    }
  }
}

###

POST {{host}}/graphql
Content-Type: application/json
X-Gateway-Secret: {{internalSecret}}
X-User-Id: {{userId}}
X-Correlation-ID: manual-my-stories-test

{
  "query": "query MyStories($userId: Long!) { myStories(userId: $userId) { author { id name avatar isVerified } latestCreate stories { __typename ... on NormalStory { id content create media { id type url } } ... on FeedPostShareStory { id content create sharedSource { id content } } ... on ReelShareStory { id content create sharedSource { id content } } } } }",
  "variables": {
    "userId": {{userId}}
  }
}

###

POST {{host}}/graphql
Content-Type: application/json
X-Gateway-Secret: {{internalSecret}}
X-User-Id: {{userId}}
X-Correlation-ID: manual-delete-story-test

{
  "query": "mutation DeleteStory($input: DeleteStoryInput!) { deleteStory(input: $input) { success message } }",
  "variables": {
    "input": {
      "authorId": {{userId}},
      "storyId": {{storyId}}
    }
  }
}

###

POST {{host}}/graphql
Content-Type: application/json
X-Gateway-Secret: {{internalSecret}}
X-User-Id: {{userId}}
X-Correlation-ID: manual-create-feed-post-test

{
  "query": "mutation CreateFeedPost($input: CreateFeedPostInput!) { createFeedPost(input: $input) { id type content privacy create authorId media { id type url } } }",
  "variables": {
    "input": {
      "authorId": {{userId}},
      "content": "Hello feed",
      "privacy": 0,
      "media": []
    }
  }
}

###

POST {{host}}/graphql
Content-Type: application/json
X-Gateway-Secret: {{internalSecret}}
X-User-Id: {{userId}}
X-Correlation-ID: manual-post-details-test

{
  "query": "query PostDetails($postIds: [Long!]!) { postDetails(postIds: $postIds) { __typename ... on FeedPostDetail { id content author { id name avatar isVerified canFollow } media { id type url } } ... on GroupPostDetail { id content author { id name avatar isVerified canFollow } group { id name avatar canJoin } media { id type url } } } }",
  "variables": {
    "postIds": [{{postId}}, {{groupPostId}}]
  }
}

###

POST {{host}}/graphql
Content-Type: application/json
X-Gateway-Secret: {{internalSecret}}
X-User-Id: {{userId}}
X-Correlation-ID: manual-record-group-visit-test

{
  "query": "mutation RecordGroupVisit($userId: Long!, $groupId: Long!) { recordGroupVisit(userId: $userId, groupId: $groupId) }",
  "variables": {
    "userId": {{userId}},
    "groupId": {{groupId}}
  }
}

###

POST {{host}}/graphql
Content-Type: application/json
X-Gateway-Secret: {{internalSecret}}
X-User-Id: {{userId}}
X-Correlation-ID: manual-visited-groups-test

{
  "query": "query VisitedGroups($userId: Long!, $limit: Int!, $cursor: String) { visitedGroups(userId: $userId, limit: $limit, cursor: $cursor) { items { id name avatar } endCursor hasNextPage } }",
  "variables": {
    "userId": {{userId}},
    "limit": 20,
    "cursor": null
  }
}

###

GET {{host}}/internal/recommendation/post-candidate-ids?userId={{userId}}&limit=20
X-Gateway-Secret: {{internalSecret}}
X-Correlation-ID: manual-candidate-test

###

PUT {{host}}/internal/users/{{userId}}/verify
Content-Type: application/json
X-Gateway-Secret: {{internalSecret}}
X-Correlation-ID: manual-verify-test

{
  "expiresAt": "2026-08-10T00:00:00Z"
}

###

DELETE {{host}}/internal/stories/expired?limit=100
X-Gateway-Secret: {{internalSecret}}
X-Correlation-ID: manual-story-cleanup-test
